#pragma once

#include "TrickDefinitions.h"
#include "TrickPrimitiveTypes.h"
#include "TrickLimits.h"

typedef enum TkConsoleMessageColor
{
	  TK_CONSOLE_MESSAGE_COLOR_BLACK
	, TK_CONSOLE_MESSAGE_COLOR_BLUE
	, TK_CONSOLE_MESSAGE_COLOR_GREEN
	, TK_CONSOLE_MESSAGE_COLOR_CYAN
	, TK_CONSOLE_MESSAGE_COLOR_RED
	, TK_CONSOLE_MESSAGE_COLOR_PURPLE
	, TK_CONSOLE_MESSAGE_COLOR_YELLOW
	, TK_CONSOLE_MESSAGE_COLOR_WHITE
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_BLACK
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_BLUE
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_GREEN
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_CYAN
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_RED
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_PURPLE
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_YELLOW
	, TK_CONSOLE_MESSAGE_COLOR_LIGHT_WHITE
	, TK_CONSOLE_MESSAGE_COLOR_ENUM_SIZE
	, TK_CONSOLE_MESSAGE_COLOR_MAX_ENUM = TK_INT32_MAX
} TkConsoleMessageColor;

void TK_CALL tkConsoleStandardOutput (tk_uint8 ForegroundColor, tk_uint8 BackgroundColor, const tk_char8* Message);
void TK_CALL tkConsoleErrorOutput    (tk_uint8 ForegroundColor, tk_uint8 BackgroundColor, const tk_char8* Message);